yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='groups'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from core.models import CreatedModel
from django.db import models

User = get_user_model()


class Group(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()


class Post(CreatedModel):
    def __str__(self):
        return f'{self.text[:15]}'

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )


class Follow (models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Автор',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст поста'),
            'group': _('Группа'),
            'image': _('Картинка'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': _('Текст поста'),
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow


def paginate_queryset(post_list, request):
    paginator = Paginator(post_list, settings.MAX_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20)
def index(request):
    post_list = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': paginate_queryset(post_list, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.group.select_related('author')
    context = {
        'group': group,
        'page_obj': paginate_queryset(post_list, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user = User.objects.get(username=username)
    post_list = user.posts.select_related('group')
    post_count = post_list.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'post_count': post_count,
        'author': user,
        'page_obj': paginate_queryset(post_list, request),
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('post')
    context = {
        'post': post,
        'post_count': post_count,
        'form': form,
        'is_edit': True,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, files=request.FILES or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=pk)
    if form.is_valid():
        post = form.save()
        post.save()
        return redirect('posts:post_detail', post_id=pk)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'is_edit': True})


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': paginate_queryset(post_list, request)
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(author=author, user=request.user).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/card.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if not group and post.group %}
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  <br>
  <a href="{% url 'posts:groups' post.group.slug %}">все записи группы</a>
  {% endif %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  {% if not forloop.last %}
  <hr>
  {% endif %}
</article>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% load user_filters %}
          {% if is_edit %}
          Редактировать запись
          {% else %}
          Добавить запись
          {% endif %}
        </div>
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            {% for field in form %}
            <div class="form-group row my-3">
              <p>{{ field.label }}<span class="required text-danger">*</span></p>
              {{ field }}
              {% endfor %}
              <small id="id_group-help" class="form-text text-muted">
                Группа, к которой будет относиться пост
              </small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
FOLLOW
{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}

{% for post in page_obj %}
{% include 'posts/card.html' %}
{% endfor %}
{% include 'includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<h1> {{ group.title }}</h1>
<p>{{ group.description }}</p>
{% for post in page_obj %}
{% include 'posts/card.html' %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
YATUBE
{% endblock %}
{% block content %}
{% for post in page_obj %}
{% include 'posts/card.html' %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Detail
{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if not group and post.group %}
      <li class="list-group-item">
        Группа: {{ post.group }}
        <a href="{% url 'posts:groups' post.group.slug %}">
          все записи группы
        </a>
      </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>{{ post_count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      {{ post }}
    </p>
    <p>
      {% if post.author == request.user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
      {% endif %}
    </p>
    {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
    {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Profile
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
    {% for post in page_obj %}
    {% include 'posts/card.html' %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
</main>
{% endblock %}