yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(
        extra_context={"var": "Зарегистрироваться"}), name='signup'),
    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),
    path('login/',
         LoginView.as_view(
             extra_context={"var": "Войти", "eto_login": "eto_login"},
             template_name='users/login.html'), name='login'),
    path('password_change/',
         PasswordChangeView.as_view(
             extra_context={"var": "Изменить пароль"},
             template_name='users/password_change_form.html'),
         name='password_change'
         ),
    path('password_change/done/',
         PasswordChangeView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_reset/',
         PasswordResetView.as_view(
             extra_context={"var": "Восстановить пароль"},
             template_name='users/password_reset_form.html'),
         name='password_reset'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/fields.html
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{{ var }}</div>
        <div class="card-body">
          {% load user_filters %}
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
              <form method="post">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help"
                        class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {{ var }}
                </button>
                  {% if eto_login %}
                  <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                    Забыли пароль?
                  </a>
                  {% endif %}
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% include 'users/fields.html' %}

{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Пароль изменен!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Сменить пароль{% endblock %}
{% block content %}
{% include 'users/fields.html' %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Пароль изменен!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

<p>Пожалуйста введите и подтвердите ваш новый пароль.</p>
<form action="" method="post">
  {% csrf_token %}

  <div class="form-group row my-3 p-3">
    {{ form.new_password1.errors }}
    <label for="id_new_password1">
      Новый пароль
      <span class="required text-danger">*</span>
    </label>
    {{ form.new_password1|addclass:'form-control' }}
    <small id="id_new_password1-help" class="form-text text-muted">
      <ul>
        <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком
          похожим на неё.
        </li>
        <li>Ваш пароль должен содержать как минимум 8 символов.</li>
        <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
        <li>Ваш пароль не может состоять только из цифр.</li>
      </ul>
    </small>
  </div>
  <div class="form-group row my-3 p-3">
    {{ form.new_password2.errors }}
    <label for="id_new_password2">
      Подтверждение нового пароля
      <span class="required text-danger">*</span>
    </label>
    {{ form.new_password2|addclass:'form-control' }}
  </div>
  <div class="col-md-6 offset-md-4">
    <button type="submit" class="btn btn-primary">
      Назначить новый пароль
    </button>
  </div>
</form>

{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}

{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Отправлено письмо
      </div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Чтобы сбросить старый пароль — введите адрес электронной почты, под
        которым вы регистрировались
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="id_email">
              Адрес электронной почты
              <span class="required text-danger">*</span>
            </label>
            <input type="email" name="email" maxlength="254"
                   class="form-control" required id="id_email">
          </div>
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% include 'users/fields.html' %}
{% endblock %} 